# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-17 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_auto_20180910_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouseClicks',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('operation_type', models.TextField()),
                ('post_id', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
    ]
