# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-20 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0007_userlogininfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogininfo',
            name='ip_address',
            field=models.TextField(default='127.0.0.1'),
        ),
    ]
